2025-10-30 16:32:15,451 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/users/me
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Utils\auth_decorator.py", line 36, in decorated
    user = User.objects(id=decoded.get("user_id")).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:32:18,040 [ERROR] in searchController: Search error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "C:\Users\oneto\Lost&Found\Controllers\searchController.py", line 127, in search_items
    items_query = LostItem.objects(combined_query)
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\document.py", line 233, in _get_collection
    if cls._meta.get("auto_create_index", True) and db.client.is_primary:
                                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1671, in is_primary
    return self._server_property("is_writable")
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1589, in _server_property
    server = (self._get_topology()).select_server(writable_server_selector, _Op.TEST)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

2025-10-30 16:32:25,758 [ERROR] in searchController: Search error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "C:\Users\oneto\Lost&Found\Controllers\searchController.py", line 136, in search_items
    total_items = items_query.count()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 143, in count
    return super().count(with_limit_and_skip)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 431, in count
    count = count_documents(
        collection=self._cursor.collection,
        filter=self._query,
        **kwargs,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\pymongo_support.py", line 46, in count_documents
    return collection.count_documents(filter=filter, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\collection.py", line 2163, in count_documents
    return self._retryable_non_cursor_read(_cmd, session, _Op.COUNT)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\collection.py", line 2177, in _retryable_non_cursor_read
    return client._retryable_read(func, self._read_preference_for(s), s, operation)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

2025-10-30 16:32:33,926 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/users/me
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Utils\auth_decorator.py", line 36, in decorated
    user = User.objects(id=decoded.get("user_id")).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:32:38,020 [ERROR] in searchController: Search error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "C:\Users\oneto\Lost&Found\Controllers\searchController.py", line 136, in search_items
    total_items = items_query.count()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 143, in count
    return super().count(with_limit_and_skip)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 431, in count
    count = count_documents(
        collection=self._cursor.collection,
        filter=self._query,
        **kwargs,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\pymongo_support.py", line 46, in count_documents
    return collection.count_documents(filter=filter, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\collection.py", line 2163, in count_documents
    return self._retryable_non_cursor_read(_cmd, session, _Op.COUNT)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\collection.py", line 2177, in _retryable_non_cursor_read
    return client._retryable_read(func, self._read_preference_for(s), s, operation)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

2025-10-30 16:32:46,178 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/users/me
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Utils\auth_decorator.py", line 36, in decorated
    user = User.objects(id=decoded.get("user_id")).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:32:54,919 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/auth/login
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Controllers\authController.py", line 92, in login
    user = User.objects(email=identifier.lower()).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:32:59,007 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/auth/login
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Controllers\authController.py", line 92, in login
    user = User.objects(email=identifier.lower()).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:33:03,090 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/auth/login
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Controllers\authController.py", line 92, in login
    user = User.objects(email=identifier.lower()).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:33:21,614 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/users/me
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Utils\auth_decorator.py", line 36, in decorated
    user = User.objects(id=decoded.get("user_id")).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 16:33:32,398 [ERROR] in app: Unexpected error: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> | Path: /api/v1/auth/login
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\oneto\Lost&Found\Controllers\authController.py", line 92, in login
    user = User.objects(email=identifier.lower()).first()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 640, in __getitem__
    for doc in clone:  # type: ignore[attr-defined]
               ^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1289, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1265, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1213, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\cursor.py", line 1108, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1938, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2047, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2014, in _retry_internal
    ).run()
      ~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2765, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2910, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 2858, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\mongo_client.py", line 1833, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69032f32cba4a4c4df499283, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-00.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-01.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.eegpm.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('cluster0-shard-00-02.eegpm.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-10-30 17:33:26,074 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 17:33:27,458 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 17:33:32,971 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 17:35:23,906 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 17:35:39,859 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 18:33:34,776 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-10-30 18:33:35,488 [ERROR] in app: Unexpected error: 405 Method Not Allowed: The method is not allowed for the requested URL. | Path: /api/v1/sales
Traceback (most recent call last):
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\oneto\Downloads\Blog\.venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
